### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by brianteeman** [joomla/docker-joomla#1]
How do we update the full readme?

**Comment by Bakual** [comment]
https://github.com/docker-library/docs/blob/master/joomla/README.md

**Comment by mbabker** [comment]
The readme on this repo comes from a stub in Docker's libraries.  I don't think there's a requirement to use it but it works fine as a starting point.

@Bakual linked to the full docs repo; definitely read the notes there.  You don't actually edit the README.md file in that folder (a bot compiles it), rather the content.md file makes up all of our "custom" content and it's wrapped by standard information.

**Comment by Bakual** [comment]
Ah. If I understand https://github.com/docker-library/docs/blob/master/README.md correct, the https://github.com/docker-library/docs/blob/master/joomla/content.md has the actual content and there is some additional stuff (Supported tags, licence, docker-compose.yml, logo, user feedback) added from the bot using an override system. Interesting thing. :smile:

**Comment by brianteeman** [comment]
That's why I asked the question :)

**Comment by brianteeman** [comment]
OK think I have done it correctly now
