### ISSUE TITLE
enable mcrypt extension

### ISSUE THREAD

**Issue by gimoh** [joomla/docker-joomla#10]
Joomla displays a warning if mcrypt is not available during installation.

Is there an issue with enabling it by default?

I personally need it for a Joomla extension, I'm OK building a derived image but I wanted to check if it would be useful in base.  Let me know and I can submit a PR sure.

**Comment by mbabker** [comment]
Added it.

**Comment by Shraa** [comment]
Don't see mcrypt support in latest image. Do you plan to include this feature as default or i need to build image by myself?

**Comment by mbabker** [comment]
Typically the image only gets updated with each CMS release unless there's a major reason to do one "out of cycle".  So when 3.6.3 is released in the next couple of weeks enabling mcrypt will be included there.
