### ISSUE TITLE
Joomla Docker Image vulnerabilities

### ISSUE THREAD

**Issue by webchun** [joomla/docker-joomla#14]
There are some vulnerability warnings in the [joomla image page](https://hub.docker.com/r/library/joomla/tags/). Is this something we need to worry about?

![image](https://cloud.githubusercontent.com/assets/4277547/20461941/87f5df84-af40-11e6-896e-b4c4f6455f06.png)

**Comment by mbabker** [comment]
It doesn't require explicit attention.  Each of the vulnerabilities are in upstream packages (mcrypt, pcre, curl, libxml2).  Running `apt-get upgrade` will allow you to update the packages, otherwise the tags are essentially snapshots at a point in time.

**Comment by webchun** [comment]
ok
