### ISSUE TITLE
Database host isn't ever going to be localhost.

### ISSUE THREAD

**Issue by bweston92** [joomla/docker-joomla#25]
Using Docker means that the likely hood of using "localhost" should be never. However there is an error shown during the installation process. This means that if you don't have access to the container because you don't know where is has been scheduled, not that you should actually go in and delete files, you cannot delete the temporary file it has asked.

![screenshot from 2017-07-27 09-27-42](https://user-images.githubusercontent.com/1764057/28661314-29dce47e-72ae-11e7-8482-2df8bd17ffef.png)

However just in case you can, there is still a bug where by the installation never succeeds, just makes indefinite HTTP requests.

![screenshot from 2017-07-27 09-30-37](https://user-images.githubusercontent.com/1764057/28661377-5b518104-72ae-11e7-8ec7-1d7d676a52e4.png)

Unless you do the following:
```
// install vim
root@444879d84e99:/var/www/html/installation/model# vi database.php 

delete:
                if (!in_array($options->db_host, $localhost))
add:
                if (false)
```

**Comment by zero-24** [comment]
Yes this is a known bug please see: https://github.com/joomla/joomla-cms/pull/17248 Thanks,

**Comment by bweston92** [comment]
@zero-24 - well actually for this part of what I said "Using Docker means that the likely hood of using "localhost" should be never." means we need to come up with a way of disabling this check all together.

The issue with having a Docker image that should work end to end is if the container is scheduled in an environment you cannot access via ssh/bash you will not have anyway of continuing. My suggestion would be to think about an environment variable `JOOMLA_INSTALLATION_DISABLE_LOCALHOST_CHECK=1`.

**Comment by zero-24** [comment]
hmm this needs to be answerd by somone who has more knowlege about docker. I'm sorry i can not help with that.
