### ISSUE TITLE
3.7.4 remote DB

### ISSUE THREAD

**Issue by billtomczak** [joomla/docker-joomla#27]
I just tried to do a fresh install with. After following instructions to delete the file file created to prove server ownership, the db install screen blocks further progress and displays the notice that I need to prove I own the server.

**Comment by mbabker** [comment]
This will be fixed fully with the 3.8.0 tag of the image.  There's a bug in the 3.7.4 installer that keeps this feature working correctly to begin with and the image change here wasn't applied until after the 3.7.4 image was tagged (and to be honest, with the way the scripts here are set up, I can't even say with certainty if I can create a `3.7.4.1` tag that would at least incorporate the change needed to make the image work).

**Comment by billtomczak** [comment]
lol - okay - so my punt was to build the container and replace the contents of www with 3.7.3. thanks!
