### ISSUE TITLE
support arm64 architecture

### ISSUE THREAD

**Issue by longquan7** [joomla/docker-joomla#30]
I want to build this image on arm64 architecture but I'm not sure that can be support arm64 architecture https://github.com/joomla/joomla-cms/releases/download/3.7.4/Joomla_3.7.4-Stable-Full_Package.zip

**Comment by zero-24** [comment]
hmm did you tried it and got any kind of error message from Joomla? I'm not aware of any issues on 64 bit systems with Joomla. As long as PHP / database / webserver etc. is running.

Thanks.

**Comment by mbabker** [comment]
Per https://github.com/docker-library/official-images#architectures-other-than-amd64 Docker itself doesn't support at least arm64v8 officially.  Right now my library file doesn't explicitly list supported architectures, but in theory the image should work with the same architectures as the [WordPress image](https://github.com/docker-library/official-images/blob/master/library/wordpress).

**Comment by longquan7** [comment]
@mbabker  If the images should work with the same architecture as the WordPress image, that can you add it to ARMv8 64-bit (arm64v8): https://hub.docker.com/u/arm64v8/

**Comment by mbabker** [comment]
I have to update the scripting to explicitly list architectures.  Since the current definition doesn't explicitly list architectures, I would assume that shouldn't affect things.

Either way catching up on some of the changes being made in other official Docker library images is on my todo list.

**Comment by mbabker** [comment]
I have to update the scripting to explicitly list architectures.  Since the current definition doesn't explicitly list architectures, I would assume that shouldn't affect things.

Either way catching up on some of the changes being made in other official Docker library images is on my todo list.

**Comment by J0WI** [comment]
This image is build on the official PHP image which supports `md64, arm32v6, arm64v8, i386, ppc64le, s390x` on Alpine and `amd64, arm32v5, arm32v6, arm32v7, arm64v8, i386, ppc64le, s390x` on Debian.
So I think all you need to do is to updating `generate-stackbrew-library.sh`.

**Comment by mbabker** [comment]
Probably, but I'm going to have to validate that step on a proper Linux environment because like I mentioned in #49 I couldn't get that function to run on my MacBook.

**Comment by J0WI** [comment]
Yeah, the [bashbrew](https://github.com/docker-library/official-images/tree/master/bashbrew#bashbrew-bashbrew) dependency is quite exotic.
But it's not that hard to set up.

**Comment by mbabker** [comment]
I'm actually going to be setting up a new Jenkins CI server for some resources in the next couple of weeks, so I'll include the tooling needed in that build (especially as I want to basically [fully automate](https://github.com/joomla/joomla-websites/issues/717) a release for this repo).

**Comment by J0WI** [comment]
#51 WFM out of the box with bashbrew.

**Comment by J0WI** [comment]
@mbabker see also https://github.com/nextcloud/docker/pull/259#issuecomment-365792424

**Comment by J0WI** [comment]
@mbabker did you manage to get the [bashbrew binary](https://doi-janky.infosiftr.net/job/bashbrew/lastSuccessfulBuild/artifact/bin/)? I think that's the only bit needed to review #51.

**Comment by mbabker** [comment]
Not yet, this weekend I intend on sitting down and work on getting my laptop updated with that and starting to provision a new Jenkins box with the required tooling.
