### ISSUE TITLE
Installation hangs in infinite loop after hitting 'Install' in third step 

### ISSUE THREAD

**Issue by frankmayer** [joomla/docker-joomla#32]
see comment section at https://hub.docker.com/_/joomla/
Users korpch, tto78 and adiq94 reported the issue and I can confirm it, so I thought to report the issue here. I might have some time to check on the issue a bit later, unless anybody else knows why this is happening and can fix the issue before that.

**Comment by mbabker** [comment]
It's probably the 3.7.4 bug.

**Comment by frankmayer** [comment]
But I am running the 3.7.5 tag... because of exactly that bug.
However I am trying to investigate at the moment. Let's see...

**Comment by frankmayer** [comment]
OK, so it was the 3.7.4 bug. 
For anyone that stumbles on this, too, I was removing and recreating the container with the correct tag, but I wasn't removing the content of the directory (volume) to which the `/var/www/html` directory was bound. This content was not overwritten by any newly created container, so it was still on 3.7.4.
Closing.
