### ISSUE TITLE
Update to Joomla 3.8.2

### ISSUE THREAD

**Issue by rainerangermeier** [joomla/docker-joomla#37]
Would be nice, since we won't have to update after creating a new container.

Additionally the official docker image should be updated as well docker-library/official-images#3699

**Comment by mbabker** [comment]
I'll get it updated tomorrow.  Just been busy and haven't had time to get this updated.

**Comment by rainerangermeier** [comment]
Thanks mate

**Comment by mbabker** [comment]
Updated the repo and PR submitted.  https://github.com/docker-library/official-images/pull/3712
