### ISSUE TITLE
Multi-arch dockerhub images

### ISSUE THREAD

**Issue by vaibhavsood** [joomla/docker-joomla#38]
Hi, I want to check if this docker image can be extended for multi-arches on dockerhub?

I have verified the dockerfile works as-is on a ppc64le machine, since the Dockerfile looks platform independent, making this image multi-arch should be a low effort https://github.com/docker-library/official-images#multiple-architectures

This issue is along similar lines https://github.com/joomla/docker-joomla/issues/30

**Comment by mbabker** [comment]
It's on my radar to work on, just haven't had much time.  Closing this as a duplicate of #30 just to keep all tracking in one spot.
