### ISSUE TITLE
Error respons from daemon when running.

### ISSUE THREAD

**Issue by stevebeer** [joomla/docker-joomla#6]
See following copied from terminal:

> ~$ docker run --name some-joomla --link some-mysql:mysql -d joomla
> Unable to find image 'joomla:latest' locally
> latest: Pulling from library/joomla
> 8b87079b7a06: Already exists 
> a3ed95caeb02: Pull complete 
> af1704cb90e1: Pull complete 
> 6acdef7ebe13: Pull complete 
> 4fc566a7c22a: Pull complete 
> b06a1bacee51: Pull complete 
> c5fc21fb6c09: Pull complete 
> df319b61c869: Pull complete 
> f958e5267409: Pull complete 
> b06010f04fa8: Pull complete 
> 17c1b5f8acff: Pull complete 
> 2ed292d591c7: Pull complete 
> 5ea0585ac6f2: Pull complete 
> 1c236307d5b0: Pull complete 
> a0e2ec0b0590: Pull complete 
> 4faac5c48b9d: Pull complete 
> 237118f80126: Pull complete 
> 32660a451e43: Pull complete 
> 6b2e9efa5569: Pull complete 
> Digest: sha256:2d174d96b0645d841b6c2e6c23b83b109fff31e3688e8789837cb834137f11fc
> Status: Downloaded newer image for joomla:latest
> docker: Error response from daemon: Could not get container for some-mysql.
> See 'docker run --help'.

**Comment by mbabker** [comment]
I don't have Docker installed anymore but IIRC you have to be running a MySQL container to be able to link to it in this manner.
